begin;

insert into facture (
    id, tenant_id, societe_interne_id, utilisateur_createur_id, tiers_id,
    contrat_id, numero_facture, libelle, type_facture, sens_facture,
    nature_facture, categorie_operation, statut_facture, statut_electronique,
    format_electronique, regime_tva, mode_paiement, devise,
    date_facture, date_emission, date_echeance, date_prestation_ou_vente,
    total_ht, total_tva, total_ttc, total_remise, montant_deja_paye,
    netapayer, resteapayer, option_tva_sur_les_debits,
    vendeur_nom, vendeur_siren, vendeur_siret, vendeur_adresse_ligne1,
    vendeur_code_postal, vendeur_ville, vendeur_pays, vendeur_email_contact,
    client_nom, client_siren, client_siret, client_adresse_facturation_ligne1,
    client_code_postal, client_ville, client_pays, client_email_contact,
    conditions_reglement, indemnite_forfaitaire_recouvrement, taux_penalites_retard,
    date_creation, date_modification
) values
(
    4,
    3,
    4,
    6,
    4,
    4,
    'FAC-REC-2026-001',
    'Facture Alpha Industrie',
    'FACTURE',
    'VENTE',
    'SERVICE',
    'PRESTATION_SERVICES',
    'VALIDEE',
    'NON_TRANSMISE',
    'AUCUN',
    'TVA_STANDARD',
    'VIREMENT',
    'EUR',
    '2026-05-13',
    '2026-05-13',
    '2026-06-12',
    '2026-05-13',
    1000.00,
    200.00,
    1200.00,
    0.00,
    0.00,
    1200.00,
    1200.00,
    false,
    'Wavy Services',
    '982880312',
    '98288031200011',
    '8 rue Raymond Marcheron',
    '92170',
    'Vanves',
    'France',
    'contact@wavyservices.fr',
    'Client Alpha Industrie SAS',
    '910000001',
    null,
    '12 boulevard de la Recette',
    '75010',
    'Paris',
    'France',
    'contact@alpha-industrie.fr',
    'Paiement à 30 jours',
    0.00,
    0.00,
    now(),
    now()
),
(
    5,
    3,
    4,
    6,
    5,
    5,
    'FAC-REC-2026-002',
    'Facture Beta Distribution',
    'FACTURE',
    'VENTE',
    'SERVICE',
    'PRESTATION_SERVICES',
    'BROUILLON',
    'NON_TRANSMISE',
    'AUCUN',
    'TVA_STANDARD',
    'VIREMENT',
    'EUR',
    '2026-05-13',
    '2026-05-13',
    '2026-06-12',
    '2026-05-13',
    1000.00,
    200.00,
    1200.00,
    0.00,
    0.00,
    1200.00,
    1200.00,
    false,
    'Wavy Services',
    '982880312',
    '98288031200011',
    '8 rue Raymond Marcheron',
    '92170',
    'Vanves',
    'France',
    'contact@wavyservices.fr',
    'Client Beta Distribution SAS',
    '910000002',
    null,
    '12 boulevard de la Recette',
    '75010',
    'Paris',
    'France',
    'contact@beta-distribution.fr',
    'Paiement à 30 jours',
    0.00,
    0.00,
    now(),
    now()
)
on conflict (id) do update set
    tenant_id = excluded.tenant_id,
    societe_interne_id = excluded.societe_interne_id,
    utilisateur_createur_id = excluded.utilisateur_createur_id,
    tiers_id = excluded.tiers_id,
    contrat_id = excluded.contrat_id,
    numero_facture = excluded.numero_facture,
    libelle = excluded.libelle,
    type_facture = excluded.type_facture,
    sens_facture = excluded.sens_facture,
    nature_facture = excluded.nature_facture,
    categorie_operation = excluded.categorie_operation,
    statut_facture = excluded.statut_facture,
    statut_electronique = excluded.statut_electronique,
    format_electronique = excluded.format_electronique,
    regime_tva = excluded.regime_tva,
    mode_paiement = excluded.mode_paiement,
    devise = excluded.devise,
    date_facture = excluded.date_facture,
    date_emission = excluded.date_emission,
    date_echeance = excluded.date_echeance,
    date_prestation_ou_vente = excluded.date_prestation_ou_vente,
    total_ht = excluded.total_ht,
    total_tva = excluded.total_tva,
    total_ttc = excluded.total_ttc,
    total_remise = excluded.total_remise,
    montant_deja_paye = excluded.montant_deja_paye,
    netapayer = excluded.netapayer,
    resteapayer = excluded.resteapayer,
    option_tva_sur_les_debits = excluded.option_tva_sur_les_debits,
    vendeur_nom = excluded.vendeur_nom,
    vendeur_siren = excluded.vendeur_siren,
    vendeur_siret = excluded.vendeur_siret,
    vendeur_adresse_ligne1 = excluded.vendeur_adresse_ligne1,
    vendeur_code_postal = excluded.vendeur_code_postal,
    vendeur_ville = excluded.vendeur_ville,
    vendeur_pays = excluded.vendeur_pays,
    vendeur_email_contact = excluded.vendeur_email_contact,
    client_nom = excluded.client_nom,
    client_siren = excluded.client_siren,
    client_siret = excluded.client_siret,
    client_adresse_facturation_ligne1 = excluded.client_adresse_facturation_ligne1,
    client_code_postal = excluded.client_code_postal,
    client_ville = excluded.client_ville,
    client_pays = excluded.client_pays,
    client_email_contact = excluded.client_email_contact,
    conditions_reglement = excluded.conditions_reglement,
    indemnite_forfaitaire_recouvrement = excluded.indemnite_forfaitaire_recouvrement,
    taux_penalites_retard = excluded.taux_penalites_retard,
    date_modification = now();

insert into ligne_facture (
    id, facture_id, reference_contrat_id, libelle, quantite, unite,
    prix_unitaire_ht, remise_pourcentage, remise_montant,
    montant_ht_avant_remise, montant_remise, montant_ht,
    taux_tva, montant_tva, montant_ttc, ordre_ligne,
    date_creation, date_modification
) values
(
    4,
    4,
    4,
    'Prestation journalière',
    2.0000,
    'JOUR',
    500.00,
    0.0000,
    0.00,
    1000.00,
    0.00,
    1000.00,
    20.0000,
    200.00,
    1200.00,
    1,
    now(),
    now()
),
(
    5,
    5,
    5,
    'Prestation journalière',
    2.0000,
    'JOUR',
    500.00,
    0.0000,
    0.00,
    1000.00,
    0.00,
    1000.00,
    20.0000,
    200.00,
    1200.00,
    1,
    now(),
    now()
)
on conflict (id) do update set
    facture_id = excluded.facture_id,
    reference_contrat_id = excluded.reference_contrat_id,
    libelle = excluded.libelle,
    quantite = excluded.quantite,
    unite = excluded.unite,
    prix_unitaire_ht = excluded.prix_unitaire_ht,
    remise_pourcentage = excluded.remise_pourcentage,
    remise_montant = excluded.remise_montant,
    montant_ht_avant_remise = excluded.montant_ht_avant_remise,
    montant_remise = excluded.montant_remise,
    montant_ht = excluded.montant_ht,
    taux_tva = excluded.taux_tva,
    montant_tva = excluded.montant_tva,
    montant_ttc = excluded.montant_ttc,
    ordre_ligne = excluded.ordre_ligne,
    date_modification = now();

insert into ventilation_tva_facture (
    id, facture_id, taux_tva, base_ht, montant_tva,
    date_creation, date_modification
) values
(
    4,
    4,
    20.0000,
    1000.00,
    200.00,
    now(),
    now()
),
(
    5,
    5,
    20.0000,
    1000.00,
    200.00,
    now(),
    now()
)
on conflict (id) do update set
    facture_id = excluded.facture_id,
    taux_tva = excluded.taux_tva,
    base_ht = excluded.base_ht,
    montant_tva = excluded.montant_tva,
    date_modification = now();

select setval(pg_get_serial_sequence('facture', 'id'), greatest((select max(id) from facture), 5), true);
select setval(pg_get_serial_sequence('ligne_facture', 'id'), greatest((select max(id) from ligne_facture), 5), true);
select setval(pg_get_serial_sequence('ventilation_tva_facture', 'id'), greatest((select max(id) from ventilation_tva_facture), 5), true);

commit;
